import { User } from "./users.types";

export const mockUsers: User[] = [
  {
    avatar: '',
    name: 'Teste',
    lastName: '1',
    email: 'teste1@example.com',
    status: 'Ativo',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '2',
    email: 'teste2@example.com',
    status: 'Pendente',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '3',
    email: 'teste3@example.com',
    status: 'Bloqueado',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '4',
    email: 'teste4@example.com',
    status: 'Ativo',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '5',
    email: 'teste5@example.com',
    status: 'Bloqueado',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'Teste',
    lastName: '1',
    email: 'teste1@example.com',
    status: 'Ativo',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '2',
    email: 'teste2@example.com',
    status: 'Pendente',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '3',
    email: 'teste3@example.com',
    status: 'Bloqueado',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '4',
    email: 'teste4@example.com',
    status: 'Ativo',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '5',
    email: 'teste5@example.com',
    status: 'Bloqueado',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'Teste',
    lastName: '1',
    email: 'teste1@example.com',
    status: 'Ativo',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '2',
    email: 'teste2@example.com',
    status: 'Pendente',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '3',
    email: 'teste3@example.com',
    status: 'Bloqueado',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '4',
    email: 'teste4@example.com',
    status: 'Ativo',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '5',
    email: 'teste5@example.com',
    status: 'Bloqueado',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'Teste',
    lastName: '1',
    email: 'teste1@example.com',
    status: 'Ativo',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '2',
    email: 'teste2@example.com',
    status: 'Pendente',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '3',
    email: 'teste3@example.com',
    status: 'Bloqueado',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '4',
    email: 'teste4@example.com',
    status: 'Ativo',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '5',
    email: 'teste5@example.com',
    status: 'Bloqueado',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '2',
    email: 'teste2@example.com',
    status: 'Pendente',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '3',
    email: 'teste3@example.com',
    status: 'Bloqueado',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '4',
    email: 'teste4@example.com',
    status: 'Ativo',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '5',
    email: 'teste5@example.com',
    status: 'Bloqueado',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'Teste',
    lastName: '1',
    email: 'teste1@example.com',
    status: 'Ativo',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '2',
    email: 'teste2@example.com',
    status: 'Pendente',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '3',
    email: 'teste3@example.com',
    status: 'Bloqueado',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '4',
    email: 'teste4@example.com',
    status: 'Ativo',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '5',
    email: 'teste5@example.com',
    status: 'Bloqueado',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '2',
    email: 'teste2@example.com',
    status: 'Pendente',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '3',
    email: 'teste3@example.com',
    status: 'Bloqueado',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '4',
    email: 'teste4@example.com',
    status: 'Ativo',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '5',
    email: 'teste5@example.com',
    status: 'Bloqueado',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'Teste',
    lastName: '1',
    email: 'teste1@example.com',
    status: 'Ativo',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '2',
    email: 'teste2@example.com',
    status: 'Pendente',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '3',
    email: 'teste3@example.com',
    status: 'Bloqueado',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '4',
    email: 'teste4@example.com',
    status: 'Ativo',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
  {
    avatar: '',
    name: 'teste',
    lastName: '5',
    email: 'teste5@example.com',
    status: 'Bloqueado',
    creationDate: new Date(),
    lastAccess: new Date(),
  },
]
